final String nullname = "Name cannot be null";
final String nullemail = "Email cannot be null";
final String validemail = "Enter a valid email address";
final String validpassword = "Mandatory 8 characters are required";
final String matchpassword = "Password does not matches";
final String validphone = "Enter a valid phone number";
final String nullbreed = "Breed cannot be null";
final String nullage = "Age cannot be null";
final String validatedescription = "Enter atleast 100 characters";
